name: '🏗️ Build and Test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - 'main'
      - 'releases/*'
  workflow_dispatch:

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: 'Setup Node.js'
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: '16.x'
          cache: 'npm'

      - name: 'Install dependencies'
        run: npm install

      - name: 'Run all NPM targets'
        run: npm run all

  testSingleFileTool: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: 'Execute test run'
        uses: ./
        with:
          toolName: 'gino-keva'
          toolRepository: 'philips-software'
          toolVersion: '2.0.0'
          urlTemplate: 'https://github.com/{{toolRepository}}/{{toolName}}/releases/download/v{{toolVersion}}/{{toolName}}'
          smokeTestTemplate: '{{toolName}} --help'

  testCompressedTool: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: 'Execute test run'
        uses: ./
        with:
          toolName: 'trivy'
          toolRepository: 'aquasecurity'
          toolVersion: '0.36.0'
          urlTemplate: 'https://github.com/{{toolRepository}}/{{toolName}}/releases/download/v{{toolVersion}}/{{toolName}}_{{toolVersion}}_{{platform}}-64bit.tar.gz'
          smokeTestTemplate: '{{toolName}} --help'
